=== SarvarKh/Electronic-Products-console-app-XML/src/main/resources/computer_parts.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="categories">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="category" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="products">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="product" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="price">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="currency" type="xs:string"/>
                                                                <xs:element name="amount" type="xs:decimal"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="availability" type="xs:positiveInteger"/>
                                                    <xs:element name="onSales" type="xs:string"/>
                                                    <xs:element name="recommended">
                                                        <xs:complexType>
                                                            <xs:attribute name="value" type="xs:boolean" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SarvarKh/Electronic-Products-console-app-XML/src/main/resources/computer_parts.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xml" href="computer_parts_transform_4.xsl" version="2.0"?>

<categories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="computer_parts.xsd">
    <category type="GPU">
        <products>
            <product>
                <name>ASUS</name>
                <price>
                    <currency>USD</currency>
                    <amount>519.99</amount>
                </price>
                <availability>1</availability>
                <onSales>Y</onSales>
                <recommended value="false"/>
            </product>
            <product>
                <name>GIGABYTE WINDFORCE GeForce</name>
                <price>
                    <currency>USD</currency>
                    <amount>599.99</amount>
                </price>
                <availability>55</availability>
                <onSales>8%</onSales>
                <recommended value="true"/>
            </product>
            <product>
                <name>51Risc AMD Radeon</name>
                <price>
                    <currency>USD</currency>
                    <amount>85.00</amount>
                </price>
                <availability>4</availability>
                <onSales>Y</onSales>
                <recommended value="false"/>
            </product>
            <product>
                <name>MSI Ventus GeForce</name>
                <price>
                    <currency>USD</currency>
                    <amount>279.99</amount>
                </price>
                <availability>55</availability>
                <onSales>8%</onSales>
                <recommended value="true"/>
            </product>
            <product>
                <name>ASRock Radeon</name>
                <price>
                    <currency>USD</currency>
                    <amount>199.99</amount>
                </price>
                <availability>3</availability>
                <onSales>5%</onSales>
                <recommended value="false"/>
            </product>
        </products>
    </category>
    <category type="CPU">
        <products>
            <product>
                <name>AMD Ryzen 9 7950X3D</name>
                <price>
                    <currency>USD</currency>
                    <amount>699.99</amount>
                </price>
                <availability>55</availability>
                <onSales>8%</onSales>
                <recommended value="true"/>
            </product>
            <product>
                <name>Intel Core i7-12700KF</name>
                <price>
                    <currency>USD</currency>
                    <amount>299.99</amount>
                </price>
                <availability>3</availability>
                <onSales>Y</onSales>
                <recommended value="false"/>
            </product>
            <product>
                <name>AMD Ryzen 7 7800X3D</name>
                <price>
                    <currency>USD</currency>
                    <amount>448.99</amount>
                </price>
                <availability>55</availability>
                <onSales>8%</onSales>
                <recommended value="false"/>
            </product>
            <product>
                <name>AMD Ryzen 5 7600</name>
                <price>
                    <currency>USD</currency>
                    <amount>223.00</amount>
                </price>
                <availability>55</availability>
                <onSales>8%</onSales>
                <recommended value="false"/>
            </product>
            <product>
                <name>Intel Core i9-12900K</name>
                <price>
                    <currency>USD</currency>
                    <amount>439.99</amount>
                </price>
                <availability>55</availability>
                <onSales>Y</onSales>
                <recommended value="true"/>
            </product>
        </products>
    </category>
    <category type="SSD">
        <products>
            <product>
                <name>Crucial P3 Plus 1TB</name>
                <price>
                    <currency>USD</currency>
                    <amount>61.99</amount>
                </price>
                <availability>1</availability>
                <onSales>9%</onSales>
                <recommended value="false"/>
            </product>
            <product>
                <name>Team Group EX2 2.5" 512GB</name>
                <price>
                    <currency>USD</currency>
                    <amount>23.99</amount>
                </price>
                <availability>2</availability>
                <onSales>Y</onSales>
                <recommended value="true"/>
            </product>
            <product>
                <name>Nextorage Japan Internal SSD 4TB</name>
                <price>
                    <currency>USD</currency>
                    <amount>289.99</amount>
                </price>
                <availability>55</availability>
                <onSales>50%</onSales>
                <recommended value="false"/>
            </product>
            <product>
                <name>ADATA PREMIUM SSD FOR PS5</name>
                <price>
                    <currency>USD</currency>
                    <amount>99.99</amount>
                </price>
                <availability>55</availability>
                <onSales>8%</onSales>
                <recommended value="true"/>
            </product>
            <product>
                <name>AITC KINGSMAN SK150 2.5" 1TB</name>
                <price>
                    <currency>USD</currency>
                    <amount>38.79</amount>
                </price>
                <availability>55</availability>
                <onSales>8%</onSales>
                <recommended value="false"/>
            </product>
        </products>
    </category>
    <category type="RAM">
        <products>
            <product>
                <name>CORSAIR Vengeance</name>
                <price>
                    <currency>USD</currency>
                    <amount>97.79</amount>
                </price>
                <availability>55</availability>
                <onSales>8%</onSales>
                <recommended value="false"/>
            </product>
            <product>
                <name>G.SKILL Trident Z5</name>
                <price>
                    <currency>USD</currency>
                    <amount>119.79</amount>
                </price>
                <availability>55</availability>
                <onSales>8%</onSales>
                <recommended value="false"/>
            </product>
            <product>
                <name>Team T-FORCE VULCAN</name>
                <price>
                    <currency>USD</currency>
                    <amount>59.79</amount>
                </price>
                <availability>55</availability>
                <onSales>8%</onSales>
                <recommended value="true"/>
            </product>
            <product>
                <name>OLOy Blade RGB</name>
                <price>
                    <currency>USD</currency>
                    <amount>209.79</amount>
                </price>
                <availability>55</availability>
                <onSales>8%</onSales>
                <recommended value="true"/>
            </product>
            <product>
                <name>GeIL ORION RGB NVMe</name>
                <price>
                    <currency>USD</currency>
                    <amount>109.79</amount>
                </price>
                <availability>55</availability>
                <onSales>8%</onSales>
                <recommended value="true"/>
            </product>
        </products>
    </category>
</categories>
